# Permalinks
#
permalink:           pretty

# Setup
title:               Riot.js
tagline:             A React-like, user interface microlibrary
url:                 http://riotjs.com
baseurl:             ""

# Markdown
markdown:           redcarpet
extensions:         [fenced_code_blocks]
redcarpet:
  extensions:       [with_toc_data,autolink,smart]

# Handling Reading
safe:               false
include:            [".htaccess"]
exclude:            ["*.tag"]
encoding:           "utf-8"
markdown_ext:       "markdown,md"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         style
  style:            :compressed

# About/contact
author:
  name:              Riot
  url:               http://riotjs.com
  email:             hello.riotjs@gmail.com

# Custom vars
major_version:       12
minor_version:       2.3

version:             2.3.12
release_date:        December 15
version_slurp:       Multi transclusion and external config file to compile your tags
repo:                https://github.com/riot/riot

# Vars needed for the compare.md page

size_min:            20.00
riot_route_size_min: 3.32

polymer:
  size:    183.00 # 118 + 48 + 17
  version: 1.2.1

webcomponents:
  size:    118.00
  version: 0.7.19

polymer_and_webcomponents_size: 301 # 183 + 118

react:
  size:    136.00
  version: 0.14.3

react_router:
  size:    48.00
  version: 1.0.2

react_mini_router:
  size:    9.91
  version: 2.0.0


# precalculated round values because of {{round}} liquid filter bug
compare:
  react: 7 # react.size / size_min
  react_router_vs_riot_router: 14 # react_router.size / riot_route_size_min
  react_mini_router_vs_riot_router: 3 # react_router.size / riot_route_size_min
  polymer_and_webcomponents: 15 # polymer_and_webcomponents_size / size_min

# Languages
translations:
  es: v2.2.4
  fr: v2.3.1
  ja: v2.2.3
  ru: v2.3.1
  zh: v2.3.1
  zh: v2.3.12
