# Permalinks
#
permalink:           pretty

# Setup
title:               Riot.js
tagline:             Simple and elegant component-based UI library
url:                 http://riot.js.org
baseurl:             ""

# Markdown
markdown:           kramdown
extensions:         [fenced_code_blocks]
redcarpet:
  extensions:       [with_toc_data,autolink,smart]

# Handling Reading
safe:               false
include:            [".htaccess"]
exclude:            ["*.tag"]
encoding:           "utf-8"
markdown_ext:       "markdown,md"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         style
  style:            :compressed

gems:
  - jemoji
  - jekyll-redirect-from

# About/contact
author:
  name:              Riot
  url:               http://riot.js.org
  email:             hello.riotjs@gmail.com

# Custom vars
minor_version:       3.11
v2_minor_version:    2.6

version:             3.11.1
v2_version:          2.6.8
version_slurp:       Add support for pnpm users
v2_version_slurp:    Security patch against XSS injections
repo:                https://github.com/riot/riot
twitter_account:     https://twitter.com/riotjs_
gitter:              https://gitter.im/riot/riot
# Vars needed for the compare.md page

size_min:            10.77
riot_route_size_min: 1.77

polymer:
  size: 49.38 # according to https://github.com/riot/riot/issues/1575#issuecomment-180869792
  version: 1.8.0

webcomponents:
  size:    16.92
  version: 0.7.24

polymer_and_webcomponents_size: 66.3 # 45.69 + 12.39 (polymer + webcomponents-lite.min.js )

react:
  size:    33.27
  version: 16.4.0

react_router:
  size:    10.95
  version: 4.1.1

react_mini_router:
  size:    4.52
  version: 2.0.0

# Languages
translations:
  es: v2.2.4
  fr: v2.5.0
  ja: v3.10.3
  ru: v2.3.1
  zh: v2.3.1
  zh: v2.3.13
