# Permalinks
#
permalink:           pretty

# Setup
title:               Riot.js
tagline:             Simple and elegant component-based UI library
url:                 http://riot.js.org
baseurl:             "/next"

# Markdown
markdown:           kramdown
highlighter:        rouge
extensions:         [fenced_code_blocks]
redcarpet:
  extensions:       [with_toc_data,autolink,smart]

# Handling Reading
safe:               false
include:            [".htaccess"]
exclude:            ["*.tag"]
encoding:           "utf-8"
markdown_ext:       "markdown,md"

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         style
  style:            :compressed

plugins:
  - jemoji
  - jekyll-target-blank

# About/contact
author:
  name:              Riot
  url:               http://riot.js.org
  email:             hello.riotjs@gmail.com
